site_name: docs.naokilog.com
copyright: 2022 naokilog.com
theme: material
extra:
  version: 0.1

markdown_extensions:
  - nl2br
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true
  - codehilite:
  

plugins:
  - glightbox
  - search
  - git-revision-date-localized

nav:
  - index.md
  - JUNOS:
    - junos/life-cycle.md
    - 設定:
      - junos/setup.md
      - junos/fundamental.md
      - junos/initialize.md
  - SRX:
    - srx/pppoe.md
  - vSRX:
    - vsrx/vsrx-vsphere-installation.md  
  - Others:
      - other/vlabs.md
      - other/useful-link.md
  - sample.md

extra_css:
  - css/extra.css
