site_name: docs.naokilog.com
copyright: 2023 naokilog.com
theme: material
extra:
  version: 0.1
  analytics:
    provider: google
    property: G-RNWVRK4RHW
  consent:
    title: Cookie consent
    description:
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.  

markdown_extensions:
  - nl2br
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true
  - codehilite:
  - pymdownx.tabbed:
      alternate_style: true
  

plugins:
  - glightbox
  - search
  - git-revision-date-localized

nav:
  - index.md
  - JUNOS:
    - junos/life-cycle.md
    - 設定:
      - junos/fundamental.md
      - junos/initialize.md
  - SRX:
    - NAT:
      - srx/nat/source-nat.md
      - srx/nat/destination-nat.md
    - srx/pppoe.md
    - vSRX:
      - srx/vsrx/vsrx-vsphere-installation.md  
  - Others:
      - other/vlabs.md
      - other/useful-link.md
  - sample.md

extra_css:
  - css/extra.css

repo_url: https://github.com/Naoria45/pages
repo_name: Naoria45/pages